import logoAsset from "@/assets/chatkode-logo.png.asset.json";

type Cleanup = () => void;

const logo = `<img src="${logoAsset.url}" alt="ChatKode" class="wordmark">`;
const button = (label:string, href:string, kind="primary") => `<a class="button button--${kind}" href="${href}">${label}<span aria-hidden="true">→</span></a>`;
const eyebrow = (n:string,label:string) => `<div class="eyebrow reveal"><span class="index" aria-hidden="true">${n}</span><i></i><span>${label}</span></div>`;
const heading = (n:string,label:string,id:string,title:string,desc:string) => `<header class="section-heading">${eyebrow(n,label)}<h2 id="${id}" class="reveal" style="--delay:80ms">${title}</h2><p class="section-copy reveal" style="--delay:140ms">${desc}</p></header>`;
const section = (id:string, content:string, raised=false) => `<section id="${id}" class="section${raised?' section--raised':''}" aria-labelledby="${id}-title"><div class="wrap">${content}</div></section>`;

const codes:Record<string,string> = {
Python:`# binary search on the answer — O(n log S)\ndef min_capacity(weights, days):\n    lo, hi = max(weights), sum(weights)\n    while lo < hi:\n        mid = (lo + hi) // 2\n        if feasible(weights, days, mid): hi = mid\n        else: lo = mid + 1\n    return lo`,
'C++':`// binary search on the answer — O(n log S)\nint minCapacity(vector<int>& w, int days) {\n  int lo = *max_element(w.begin(), w.end());\n  int hi = accumulate(w.begin(), w.end(), 0);\n  while (lo < hi) {\n    int mid = lo + (hi - lo) / 2;\n    feasible(w, days, mid) ? hi = mid : lo = mid + 1;\n  }\n  return lo;\n}`,
JavaScript:`// binary search on the answer — O(n log S)\nfunction minCapacity(weights, days) {\n  let lo = Math.max(...weights);\n  let hi = weights.reduce((a, b) => a + b, 0);\n  while (lo < hi) {\n    const mid = (lo + hi) >> 1;\n    if (feasible(weights, days, mid)) hi = mid;\n    else lo = mid + 1;\n  }\n  return lo;\n}`,
TypeScript:`// binary search on the answer — O(n log S)\nexport function minCapacity(weights: number[], days: number): number {\n  let lo = Math.max(...weights);\n  let hi = weights.reduce((a, b) => a + b, 0);\n  while (lo < hi) {\n    const mid = (lo + hi) >> 1;\n    if (feasible(weights, days, mid)) hi = mid;\n    else lo = mid + 1;\n  }\n  return lo;\n}`,
Rust:`// binary search on the answer — O(n log S)\npub fn min_capacity(w: &[u32], days: u32) -> u32 {\n    let (mut lo, mut hi) = (*w.iter().max().unwrap(), w.iter().sum());\n    while lo < hi {\n        let mid = lo + (hi - lo) / 2;\n        if feasible(w, days, mid) { hi = mid } else { lo = mid + 1 }\n    }\n    lo\n}`
};
const escape = (s:string) => s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
const syntax = (s:string) => escape(s)
 .replace(/(#[^\n]*|\/\/[^\n]*)/g,'<span class="syn-com">$1</span>')
 .replace(/\b(def|from|import|return|for|in|while|if|else|let|const|function|export|int|pub|fn|mut|u32|number)\b/g,'<span class="syn-key">$1</span>')
 .replace(/\b(feasible|min_capacity|minCapacity|max|sum|reduce|iter|unwrap)\b/g,'<span class="syn-fn">$1</span>');
const codePanel = (title:string, code:string, extra='') => `<div class="panel code-panel" data-code-panel><div class="panel-bar"><span><b></b>${title}</span><button class="copy" type="button" aria-live="polite">copy</button></div>${extra}<pre><code>${syntax(code)}</code></pre><div class="panel-foot">Illustrative code shown for demonstration.</div></div>`;

const nav = ['Product:#product','Capabilities:#capabilities','Developers:#developers','About:#about'];
const pipeline = [['01','Question','A problem stated in plain language, with its constraints and edge cases surfaced first.'],['02','Analysis','Inputs, invariants and failure modes are separated from the noise before anything is written.'],['03','Mathematical model','The problem is expressed formally — sets, recurrences, bounds — so the shape of the solution is visible.'],['04','Algorithm','A concrete procedure with a stated complexity, chosen against the constraints, not against a template.'],['05','Implementation','Readable code that matches the reasoning above it, in the language you actually ship.']];

export function createChatKodePage(){
 const heroCode = `# problem: schedule jobs to minimise total lateness\nfrom heapq import heappush, heappop\n\n# model: jobs (p_i, d_i) — greedy by due date is optimal (EDD)\ndef min_total_lateness(jobs):\n    jobs = sorted(jobs, key=lambda j: j[1])   # O(n log n)\n    t = lateness = 0\n    for p, d in jobs:\n        t += p\n        lateness += max(0, t - d)\n    return lateness`;
 const navLinks=nav.map(x=>{const [l,h]=x.split(':');return `<li><a href=":${h}">${l}</a></li>`}).join('').replaceAll('href=":#','href="#');
 return `<div class="ck" id="top">
 <a href="#main" class="skip-link">Skip to main content</a>
 <header class="navbar"><div class="nav-wrap"><a href="#top" aria-label="ChatKode home">${logo}</a><nav aria-label="Primary"><ul>${navLinks}</ul></nav><div class="nav-actions">${button('Try ChatKode','#try')}<button class="menu-toggle" type="button" aria-expanded="false" aria-controls="mobile-menu" aria-label="Open menu"><span></span><span></span><span></span></button></div></div><nav id="mobile-menu" aria-label="Mobile"><ul>${navLinks}</ul>${button('Try ChatKode','#try')}</nav></header>
 <main id="main"><section class="hero"><div class="hero-atmosphere" aria-hidden="true"><div class="grid-bg"></div><svg viewBox="0 0 1200 760" preserveAspectRatio="xMidYMid slice"><path d="M40 210H220l46-46h154l50 50h170"/><path d="M720 92v76l52 52h270l72 72"/><path d="M90 540h130l52-52h190"/><path d="M850 560h130l48-48h132"/></svg></div><div class="wrap hero-grid"><div><p class="eyebrow hero-in"><b></b>AI for builders</p><h1 class="hero-in">Think in code.<br>Solve in mathematics.<br><span class="gradient-text">Build with ChatKode.</span></h1><p class="hero-lead hero-in">ChatKode is a developer-focused AI from Kode Developers, made for programming, mathematics, algorithms and technical problem solving. It has been specifically taught mathematics to strengthen its reasoning on complex algorithmic work.</p><div class="hero-buttons hero-in">${button('Try ChatKode','#try')}${button('Explore capabilities','#capabilities','outline')}</div><dl class="hero-facts hero-in"><div><dt>Domain</dt><dd>Engineering</dd></div><div><dt>Focus</dt><dd>Reasoning</dd></div><div><dt>Built by</dt><dd>Kode Developers</dd></div></dl></div><div class="hero-code hero-in">${codePanel('lateness.py',heroCode).replace('Illustrative code shown for demonstration.','● model: greedy / EDD &nbsp; complexity O(n log n)')}</div></div></section>
 <div class="cap-strip reveal"><div class="wrap">${['Code','Math','Algorithms','Reasoning','Engineering'].map(x=>`<span>${x}</span>`).join('')}</div></div>
 ${section('product',`<div class="split"><div>${heading('01','What is ChatKode','product-title','Not a chatbot that happens to write code. A tool built around <em>how engineers think</em>.','')}<div class="panel response reveal"><small>Response shape</small><p><i>constraints</i> n ≤ 10⁵ · values ≤ 10⁹ · time 1s</p><p><i>representation</i> sorted array + two pointers</p><p><i>complexity</i> time O(n log n) · space O(1)</p><p><i>risk</i> overflow on sum → use 64-bit</p></div></div><div class="prose reveal"><p>Most conversational assistants treat a programming question like any other question: produce fluent text, stop. ChatKode is built for the part that comes before the text — reading the constraints, choosing a representation, and committing to an approach that can be defended.</p><p>It was made by <strong>Kode Developers</strong> for developers, programmers and technically minded people who care whether a solution is <strong>correct</strong>, not only whether it <strong>compiles</strong>.</p><ul class="rows"><li><b>Reasoning first</b><span>Constraints and structure before syntax.</span></li><li><b>Mathematically taught</b><span>Trained on mathematics to sharpen formal reasoning.</span></li><li><b>Algorithmic bias</b><span>Prefers a stated method over a guessed snippet.</span></li><li><b>Engineering register</b><span>Speaks in complexity, invariants and trade-offs.</span></li></ul></div></div>`)}
 ${section('capabilities',`${heading('02','Built for complex problems','capabilities-title','A problem does not become code in one step. It goes through <em>a pipeline</em>.','ChatKode works the way an engineer works: understand, formalise, choose a method, then implement. Each stage is visible, so you can disagree with it.')}<ol class="pipeline"><i class="rail"></i>${pipeline.map(x=>`<li><b>${x[0]}</b><div><h3>${x[1]}</h3><p>${x[2]}</p></div></li>`).join('')}</ol><p class="note reveal">Pipeline is illustrative of how responses are structured — not a guarantee of output.</p>`,true)}
 ${section('mathematics',`<div class="split sticky-split">${heading('03','Mathematics','mathematics-title','Taught mathematics, so the <mark>reasoning</mark> holds before the code does.','ChatKode has been specifically taught mathematics to improve how it works with mathematical problems and complex algorithms. In practice that means a problem is turned into something you can argue about — bounds, monotonicity, recurrences — before an implementation is proposed.')}<div class="math-stack">${[['Problem','Split an array into k parts, minimising the largest part sum.'],['Formalise','minimise max₁≤j≤k Σ_{i∈Pⱼ} aᵢ subject to ⋃Pⱼ = A'],['Simplify','feasible(x) is monotone in x → the answer space is sorted'],['Algorithmic form','binary search x ∈ [max aᵢ, Σ aᵢ] · check feasible(x) greedily']].map((x,i)=>`<article class="panel reveal"><small>0${i+1} &nbsp; ${x[0]}</small><p>${x[1]}</p></article>`).join('')}<figure class="panel reveal"><small>Worked notation</small><div class="notation"><span>T(n) = 2·T(n/2) + O(n) ⇒ O(n log n)</span><span>Σᵢ₌₁ⁿ i = n(n+1)/2</span><span>gcd(a, b) = gcd(b, a mod b)</span><span>|A ∪ B| = |A| + |B| − |A ∩ B|</span></div><svg viewBox="0 0 320 90" role="img" aria-label="Growth comparison of linear, n log n and quadratic curves"><path d="M0 88 L320 44"/><path class="gold" d="M0 88 C110 78,200 52,320 16"/><path class="blue dash" d="M0 88 C150 86,235 60,300 2"/></svg></figure></div></div>`)}
 ${section('coding',`${heading('04','Coding','coding-title','From a stated problem to an implementation you can <em>read line by line</em>.','The same problem, carried across three panels: what was asked, how it was reasoned about, and what it became. Language tabs are a demonstration of the surface, not a claim about tooling.')}<div class="coding-grid"><article class="panel reveal"><small>Problem</small><p>Packages must ship within <em>d</em> days, in order. Find the smallest daily capacity that still meets the deadline.</p><dl><div><dt>input</dt><dd>weights[], d</dd></div><div><dt>output</dt><dd>min capacity</dd></div><div><dt>order</dt><dd>preserved</dd></div></dl></article><article class="panel reveal"><small>Reasoning</small><ol>${['Answer is monotone: if capacity x works, x+1 works.','So search over the answer, not the partitions.','Lower bound = max(weights); upper bound = sum(weights).','feasible(x): sweep once, open a new day when the load exceeds x.'].map((x,i)=>`<li><b>${i+1}.</b>${x}</li>`).join('')}</ol><p class="gold-text">complexity: O(n log Σaᵢ)</p></article><div class="reveal">${codePanel('min_capacity',codes.Python,`<div class="tabs" role="tablist" aria-label="Language">${Object.keys(codes).map((x,i)=>`<button role="tab" aria-selected="${i===0}" tabindex="${i===0?0:-1}" data-lang="${x}">${x}</button>`).join('')}</div>`)}</div></div><p class="note reveal">Panels scroll horizontally on small screens.</p>`,true)}
 ${section('algorithms',`${heading('05','Algorithms','algorithms-title','An algorithm is a <em>structure</em>, not a snippet.','Data enters, gets shaped, gets traversed, gets checked. ChatKode is oriented around naming those stages explicitly so the result can be reviewed like any other engineering artefact.')}<div class="panel algo reveal"><svg viewBox="0 0 640 200" role="img" aria-label="Input flows through normalise and order into scan, then verification and output"><g class="edges"><path d="M94 100C130 100 130 46 174 46"/><path d="M94 100C130 100 130 154 174 154"/><path d="M266 46C310 46 310 100 356 100"/><path d="M266 154C310 154 310 100 356 100"/><path d="M424 100C470 100 470 46 504 46"/><path class="success" d="M424 100C470 100 470 154 504 154"/></g>${[['in',60,100,'input','raw sequence'],['norm',220,46,'normalise','bounds & types'],['sort',220,154,'order','O(n log n)'],['scan',390,100,'scan','single pass'],['check',550,46,'verify','invariant holds'],['out',550,154,'output','answer + proof']].map(n=>`<g class="algo-node" tabindex="0" aria-label="${n[3]}: ${n[4]}"><rect x="${Number(n[1])-46}" y="${Number(n[2])-20}" width="92" height="40" rx="4"/><text x="${n[1]}" y="${Number(n[2])-2}">${n[3]}</text><text class="sub" x="${n[1]}" y="${Number(n[2])+12}">${n[4]}</text></g>`).join('')}</svg></div><ul class="feature-grid"><li><b>Deterministic shape</b><span>Same stages, whatever the problem size.</span></li><li><b>Stated complexity</b><span>Cost named alongside the method.</span></li><li><b>Reviewable</b><span>Every stage can be challenged on its own.</span></li></ul>`)}
 ${section('developers',`<div class="split"><div>${heading('06','Developer experience','developers-title','Made for the hours between <em>a hard problem</em> and a working build.','Technical vocabulary, precise output, no filler. ChatKode is designed to sit next to the work you were already doing — reading code, sketching an approach, checking whether an idea survives its own edge cases.')}<ul class="feature-grid two"><li><b>Precise register</b><span>Answers in complexity and invariants.</span></li><li><b>Edge-case pressure</b><span>Failure modes named, not skipped.</span></li><li><b>Multi-language</b><span>Reads and writes across common stacks.</span></li><li><b>Explain mode</b><span>Walks the reasoning, not only the result.</span></li></ul></div><div class="reveal">${codePanel('chatkode — zsh',`$ chatkode explain --file scheduler.rs --focus complexity\n> reading scheduler.rs · 214 lines\n> hot path: fn assign() — nested loop over tasks × workers\n> current: O(t · w) · suggested: bucket by deadline → O(t log t)\n$ chatkode derive --from 'minimise max load' --target algorithm\n> monotone predicate found · binary search on answer`)}</div></div>`,true)}
 ${section('approach',`${heading('07','Why ChatKode','approach-title','Two ways to answer a technical question. ChatKode is built around <em>the second</em>.','A comparison of approaches, not of products. Both have their place — ChatKode is deliberately shaped for the right-hand column.')}<div class="comparison"><header><b>Generic assistant</b><b>Developer-focused AI</b></header>${[['General conversation','Technical problem solving'],['Basic answers','Structured reasoning'],['Code generation','Algorithmic thinking'],['Restates the prompt','States constraints and complexity'],['One shape for every task','Model first, then implement']].map(x=>`<div class="reveal"><span>${x[0]}</span><strong>› ${x[1]}</strong></div>`).join('')}</div>`)}
 ${section('about',`<div class="split"><div>${eyebrow('08','The company')}<h2 id="about-title" class="company reveal">ChatKode <span>by <strong>Kode Developers</strong></span></h2></div><div class="prose reveal"><h3>A public-facing product from a team that builds software for a living.</h3><p>Kode Developers created ChatKode as its developer-facing AI product. The intent is narrow on purpose: serve people who write code, model problems and care about how a solution was reached — and keep the product accountable to that audience.</p><small>Kode Developers · product: ChatKode</small></div></div>`,true)}
 ${section('human-first',`<div class="split sticky-split">${heading('09','Human-first AI','human-first-title','Not just a capable AI. An AI with <span class="green-text">boundaries</span>.','We didn’t just build ChatKode to know how to help. We built it around the judgment that knowing how is not the same as deciding whether something should be done.')}<div class="human-content"><p class="reveal">ChatKode is intended to help people build, learn, reason and solve problems. Its capability remains in service of the person using it — within appropriate safety, ethical and legal boundaries. It should assist human decisions, not become the authority behind them.</p><div class="panel human-system reveal"><small>Human → AI → human</small><div class="human-flow"><article><small>Directs</small><b>Human</b><span>asks · sets intent</span></article><i><span>legitimate goal</span></i><article>${logo}<span>helps · reasons · builds</span></article><i><span>assistance</span></i><article class="green"><small>Reviews</small><b>Human decision</b><span>checks · decides · uses</span></article></div><p>The person remains responsible at both ends of the system.</p></div><ul class="feature-grid two">${[['01','Human first','AI should amplify human capability, not replace human agency.'],['02','Know your limits','Being capable of something does not make every use appropriate.'],['03','Help, don’t control','ChatKode exists to assist the person using it, not to make itself the authority.'],['04','Use it responsibly','AI is a tool. How that tool is used still matters.']].map(x=>`<li class="reveal"><b>${x[0]} · ${x[1]}</b><span>${x[2]}</span></li>`).join('')}</ul><div class="panel capability reveal"><div><small>Capable of</small><p>generating · reasoning · explaining · transforming · assisting</p></div><b aria-label="does not equal">≠</b><div><small>Authority to</small><p>decide for people · control people · override human agency</p></div></div><blockquote class="reveal">${logo}<p>Kode Developers builds the tool. People decide how they use it.</p><small>AI can make mistakes, and important outputs deserve review. Build with it. Think with it. Verify when it matters.</small></blockquote></div></div>`)}
 <section id="try" class="cta"><div class="grid-bg" aria-hidden="true"></div><div class="cta-inner"><p class="eyebrow reveal">Start building</p><h2 class="reveal">Bring it a problem that <span class="gradient-text">actually resists</span>.</h2><p class="reveal">Coding, mathematics, algorithms and reasoning — in one developer-focused product from Kode Developers. Build boldly. Think responsibly.</p>${button('See ChatKode work','#coding')}<a href="#about" class="text-link">Learn more about Kode Developers →</a></div></section>
 </main><footer><div class="wrap footer-grid"><div>${logo}<p>A developer-focused AI for code, mathematics and algorithms.</p><small>by Kode Developers</small></div><nav aria-label="Footer"><a href="#product">Overview</a><a href="#capabilities">Capabilities</a><a href="#mathematics">Mathematics</a><a href="#coding">Coding</a><a href="#algorithms">Algorithms</a><a href="#developers">Developer experience</a><a href="#approach">Approach</a><a href="#about">Kode Developers</a></nav></div><div class="wrap copyright"><span>© <b data-year></b> Kode Developers. All rights reserved.</span><span>ChatKode — AI for code, mathematics & algorithms</span></div></footer></div>`;
}

export function initChatKode(root:HTMLElement):Cleanup {
 const cleanups:Cleanup[]=[]; const reduced=matchMedia('(prefers-reduced-motion: reduce)');
 const navEl=root.querySelector('.navbar'); const toggle=root.querySelector<HTMLButtonElement>('.menu-toggle'); const menu=root.querySelector<HTMLElement>('#mobile-menu');
 const scroll=()=>navEl?.classList.toggle('scrolled',scrollY>24); addEventListener('scroll',scroll,{passive:true}); scroll(); cleanups.push(()=>removeEventListener('scroll',scroll));
 const close=()=>{toggle?.setAttribute('aria-expanded','false');toggle?.setAttribute('aria-label','Open menu');menu?.classList.remove('open');document.body.style.overflow=''};
 toggle?.addEventListener('click',()=>{const open=toggle.getAttribute('aria-expanded')!=='true';toggle.setAttribute('aria-expanded',String(open));toggle.setAttribute('aria-label',open?'Close menu':'Open menu');menu?.classList.toggle('open',open);document.body.style.overflow=open?'hidden':''}); menu?.querySelectorAll('a').forEach(a=>a.addEventListener('click',close));
 const reveals=[...root.querySelectorAll<HTMLElement>('.reveal,.section')]; if(reduced.matches) reveals.forEach(x=>x.classList.add('visible')); else {const obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible'); if(e.target.classList.contains('reveal'))obs.unobserve(e.target)}}),{threshold:.14,rootMargin:'0px 0px -8%'}); reveals.forEach(x=>obs.observe(x));cleanups.push(()=>obs.disconnect())}
 const heroEls=[...root.querySelectorAll<HTMLElement>('.hero-in')]; heroEls.forEach((x,i)=>setTimeout(()=>x.classList.add('visible'),reduced.matches?0:60+i*130));
 root.querySelectorAll<HTMLButtonElement>('.copy').forEach(btn=>btn.addEventListener('click',async()=>{const code=btn.closest('[data-code-panel]')?.querySelector('code')?.textContent??'';try{await navigator.clipboard.writeText(code);btn.textContent='copied';setTimeout(()=>btn.textContent='copy',1600)}catch{btn.textContent='copy'}}));
 root.querySelectorAll<HTMLButtonElement>('[data-lang]').forEach(btn=>btn.addEventListener('click',()=>{const panel=btn.closest('[data-code-panel]'); const lang=btn.dataset.lang; if(!panel||!lang)return; panel.querySelectorAll('[data-lang]').forEach(x=>{x.setAttribute('aria-selected',String(x===btn));x.setAttribute('tabindex',x===btn?'0':'-1')}); const code=panel.querySelector('code');if(code)code.innerHTML=syntax(codes[lang]??'')}));
 root.querySelectorAll('.tabs').forEach(t=>t.addEventListener('keydown',(e)=>{if(!(e instanceof KeyboardEvent)||!['ArrowLeft','ArrowRight'].includes(e.key))return;const bs=[...t.querySelectorAll<HTMLButtonElement>('button')];const i=bs.indexOf(document.activeElement as HTMLButtonElement);const n=bs[(i+(e.key==='ArrowRight'?1:-1)+bs.length)%bs.length];n?.click();n?.focus()}));
 root.querySelectorAll<SVGGElement>('.algo-node').forEach(node=>{const set=(on:boolean)=>{node.closest('svg')?.querySelectorAll('.algo-node').forEach(n=>n.classList.toggle('dim',on&&n!==node));node.classList.toggle('active',on)};node.addEventListener('mouseenter',()=>set(true));node.addEventListener('mouseleave',()=>set(false));node.addEventListener('focus',()=>set(true));node.addEventListener('blur',()=>set(false))});
 root.querySelectorAll<HTMLElement>('[data-year]').forEach(x=>x.textContent=String(new Date().getFullYear()));
 return ()=>{close();cleanups.forEach(fn=>fn())};
}
